#! /bin/bash

for ii in *.com ; do
    i=${ii%.com}

    cat > ${i}.sh <<EOF
#! /bin/bash
#SBATCH -t 28-00:00
#SBATCH -J ${i}
#SBATCH -o ${i}.out
#SBATCH -e ${i}.err
#SBATCH -N 1
#SBATCH -n 32
#SBATCH --mem-per-cpu=4000M
#SBATCH --account=rrg-dilabiog

	export g16root=/opt/software/gaussian
	. \$g16root/g16/bsd/g16.profile
       
input=${i}

cd \$SLURM_SUBMIT_DIR

mkdir temporarydir_\${input}
mv    \${input}.* temporarydir_\${input}
cd    temporarydir_\${input}

g16 < \${input}.com >& \${input}.log

mv \${input}.* ..

cd ..

rm -r temporarydir_\${input}

EOF
done
